package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Subproject1_Xxx'
in the project with id = 'Subproject1', and delete the patch script.
*/
create(RelativeId("Subproject1"), BuildType({
    templates(RelativeId("TemplateForParent"))
    id("Subproject1_Xxx")
    name = "xxx"
}))

