package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Subproject2_Yyy'
in the project with id = 'Subproject2', and delete the patch script.
*/
create(RelativeId("Subproject2"), BuildType({
    templates(RelativeId("TemplateForParent"))
    id("Subproject2_Yyy")
    name = "yyy"
}))

