package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Template
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'TemplateTttt'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Template({
    id("TemplateTttt")
    name = "templateTttt"

    steps {
        script {
            name = "ttt"
            id = "RUNNER_22"
            scriptContent = "tttt"
        }
    }
}))

